// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExZNd632s71NeWsBmul1TxxmieD_Ejr8',
    appId: '1:288165151050:web:fbab87ecebdc68afd281b3',
    messagingSenderId: '288165151050',
    projectId: 'learning-15905',
    authDomain: 'learning-15905.firebaseapp.com',
    storageBucket: 'learning-15905.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6zqD5hlvSb5qoNjxF7fwYV4xPdxuqDE',
    appId: '1:288165151050:android:de8922570cb9c3eed281b3',
    messagingSenderId: '288165151050',
    projectId: 'learning-15905',
    storageBucket: 'learning-15905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrApTtdkebGT1aT_r4RORoycux6fNT_3s',
    appId: '1:288165151050:ios:72b4723026a8c8b3d281b3',
    messagingSenderId: '288165151050',
    projectId: 'learning-15905',
    storageBucket: 'learning-15905.appspot.com',
    iosClientId: '288165151050-ngulkimd023ms8siucv34eibkkhlkphn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrApTtdkebGT1aT_r4RORoycux6fNT_3s',
    appId: '1:288165151050:ios:72b4723026a8c8b3d281b3',
    messagingSenderId: '288165151050',
    projectId: 'learning-15905',
    storageBucket: 'learning-15905.appspot.com',
    iosClientId: '288165151050-ngulkimd023ms8siucv34eibkkhlkphn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );
}
